// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Persistence.Context;

#nullable disable

namespace MyApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323180000_SeedDefaultDiseaseTreatmentSolutions")]
    partial class SeedDefaultDiseaseTreatmentSolutions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("activity_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ActivityLogId");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ImageUpload", b =>
                {
                    b.Property<int>("UploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("upload_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UploadId"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("int")
                        .HasColumnName("image_height");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("int")
                        .HasColumnName("image_width");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("original_filename");

                    b.Property<string>("StoredFilename")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("stored_filename");

                    b.Property<string>("UploadStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("upload_status");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UploadId")
                        .HasName("PK__image_up__A13DEF58E7C35B7D");

                    b.HasIndex(new[] { "UploadStatus" }, "idx_upload_status");

                    b.HasIndex(new[] { "UploadedAt" }, "idx_uploaded_at");

                    b.HasIndex(new[] { "UserId" }, "idx_user_id");

                    b.ToTable("image_uploads", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ModelVersion", b =>
                {
                    b.Property<int>("ModelVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("model_version_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelVersionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_path");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("resnet18")
                        .HasColumnName("model_type");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("version");

                    b.HasKey("ModelVersionId")
                        .HasName("PK__model_ve__D71A143AFF269214");

                    b.HasIndex(new[] { "IsActive" }, "idx_is_active");

                    b.HasIndex(new[] { "IsDefault" }, "idx_is_default");

                    b.HasIndex(new[] { "ModelName", "Version" }, "unique_model_version")
                        .IsUnique();

                    b.ToTable("model_versions", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Prediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prediction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5, 4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IllnessId")
                        .HasColumnType("int")
                        .HasColumnName("illness_id");

                    b.Property<int?>("ModelVersionId")
                        .HasColumnType("int")
                        .HasColumnName("model_version_id");

                    b.Property<string>("PredictedClass")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("predicted_class");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("int")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("TopNPredictions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("top_n_predictions");

                    b.Property<int?>("TreeId")
                        .HasColumnType("int")
                        .HasColumnName("tree_id");

                    b.Property<int>("UploadId")
                        .HasColumnType("int")
                        .HasColumnName("upload_id");

                    b.HasKey("PredictionId")
                        .HasName("PK__predicti__F1AE77BF0DB959B5");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_created_at_pred");

                    b.HasIndex(new[] { "IllnessId" }, "idx_illness_id_pred");

                    b.HasIndex(new[] { "ModelVersionId" }, "idx_model_version_id");

                    b.HasIndex(new[] { "TreeId" }, "idx_tree_id_pred");

                    b.HasIndex(new[] { "UploadId" }, "idx_upload_id_pred");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ProcessedImage", b =>
                {
                    b.Property<int>("ProcessedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("processed_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessedId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PreprocessingSteps")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preprocessing_steps");

                    b.Property<string>("ProcessedFilePath")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("processed_file_path");

                    b.Property<int>("UploadId")
                        .HasColumnType("int")
                        .HasColumnName("upload_id");

                    b.HasKey("ProcessedId")
                        .HasName("PK__processe__EE42C2329266644E");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_created_at");

                    b.HasIndex(new[] { "UploadId" }, "idx_upload_id");

                    b.ToTable("processed_images", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PredictionId")
                        .HasColumnType("int")
                        .HasColumnName("prediction_id");

                    b.Property<string>("Rating1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rating");

                    b.HasKey("RatingId")
                        .HasName("PK__ratings__D35B278B2C910B23");

                    b.HasIndex(new[] { "PredictionId" }, "idx_prediction_id");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refresh_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("JtiHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jti_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RefreshTokenId")
                        .HasName("PK__refresh___B0A1F7C766869DA0");

                    b.HasIndex(new[] { "JtiHash" }, "UQ__refresh___11D28A4E0314AB34")
                        .IsUnique();

                    b.HasIndex(new[] { "IsRevoked" }, "idx_refresh_revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ResetPasswordToken", b =>
                {
                    b.Property<int>("ResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reset_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResetTokenId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ResetTokenId")
                        .HasName("PK__reset_pa__9D878429B4763C71");

                    b.HasIndex(new[] { "TokenHash" }, "UQ__reset_pa__9F6BDB13B2CE46D6")
                        .IsUnique();

                    b.HasIndex(new[] { "IsUsed" }, "idx_reset_used");

                    b.ToTable("reset_password_tokens", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.SolutionCondition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("condition_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"));

                    b.Property<decimal?>("MinConfidence")
                        .HasColumnType("decimal(5, 4)")
                        .HasColumnName("min_confidence");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("SolutionId")
                        .HasColumnType("int")
                        .HasColumnName("solution_id");

                    b.Property<string>("WeatherCondition")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("weather_condition");

                    b.HasKey("ConditionId")
                        .HasName("PK__solution__8527AB15A8E109B8");

                    b.HasIndex("SolutionId");

                    b.ToTable("solution_conditions", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("setting_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("setting_group");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("setting_key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("setting_value");

                    b.HasKey("SettingId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreatmentSolution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("solution_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolutionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IllnessId")
                        .HasColumnType("int")
                        .HasColumnName("illness_id");

                    b.Property<int?>("IllnessStageId")
                        .HasColumnType("int")
                        .HasColumnName("illness_stage_id");

                    b.Property<decimal?>("MinConfidence")
                        .HasColumnType("decimal(5, 4)")
                        .HasColumnName("min_confidence");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("SolutionName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("solution_name");

                    b.Property<string>("SolutionType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("solution_type");

                    b.Property<int>("TreeStageId")
                        .HasColumnType("int")
                        .HasColumnName("tree_stage_id");

                    b.HasKey("SolutionId")
                        .HasName("PK__treatmen__EA431C4996C956A8");

                    b.HasIndex("IllnessId");

                    b.HasIndex("TreeStageId");

                    b.ToTable("treatment_solutions", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Tree", b =>
                {
                    b.Property<int>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tree_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_path");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("scientific_name");

                    b.Property<string>("TreeName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tree_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("TreeId")
                        .HasName("PK__trees__B80FA69880146702");

                    b.HasIndex(new[] { "ScientificName" }, "idx_scientific_name");

                    b.HasIndex(new[] { "TreeName" }, "idx_tree_name");

                    b.ToTable("trees", null, t =>
                        {
                            t.HasTrigger("trg_trees_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreeIllness", b =>
                {
                    b.Property<int>("IllnessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("illness_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IllnessId"));

                    b.Property<string>("Causes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("causes");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("IllnessName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("illness_name");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("scientific_name");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symptoms");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IllnessId")
                        .HasName("PK__tree_ill__F28BCB8F81CADBC2");

                    b.HasIndex(new[] { "IllnessName" }, "idx_illness_name");

                    b.ToTable("tree_illnesses", null, t =>
                        {
                            t.HasTrigger("trg_tree_illnesses_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreeIllnessRelationship", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("relationship_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationshipId"));

                    b.Property<int>("IllnessId")
                        .HasColumnType("int")
                        .HasColumnName("illness_id");

                    b.Property<int>("TreeId")
                        .HasColumnType("int")
                        .HasColumnName("tree_id");

                    b.HasKey("RelationshipId")
                        .HasName("PK__tree_ill__C0CFD5549315CE3C");

                    b.HasIndex(new[] { "IllnessId" }, "idx_illness_id");

                    b.HasIndex(new[] { "TreeId" }, "idx_tree_id");

                    b.HasIndex(new[] { "TreeId", "IllnessId" }, "unique_tree_illness")
                        .IsUnique();

                    b.ToTable("tree_illness_relationships", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreeStage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("StageName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stage_name");

                    b.HasKey("StageId")
                        .HasName("PK__tree_sta__CFC787609D9C4079");

                    b.ToTable("tree_stages", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("account_status");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_image_path");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370FEF387219");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E61643CD88CAE")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__users__F3DBC572B30B5982")
                        .IsUnique();

                    b.HasIndex(new[] { "AccountStatus" }, "idx_account_status");

                    b.HasIndex(new[] { "Email" }, "idx_email");

                    b.HasIndex(new[] { "Username" }, "idx_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasTrigger("trg_users_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_activity_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ImageUpload", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.User", "User")
                        .WithMany("ImageUploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_upload_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.TreeIllness", "Illness")
                        .WithMany("Predictions")
                        .HasForeignKey("IllnessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_prediction_illness");

                    b.HasOne("MyApp.Domain.Entities.ModelVersion", "ModelVersion")
                        .WithMany("Predictions")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_prediction_model");

                    b.HasOne("MyApp.Domain.Entities.Tree", "Tree")
                        .WithMany("Predictions")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_prediction_tree");

                    b.HasOne("MyApp.Domain.Entities.ImageUpload", "Upload")
                        .WithMany("Predictions")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prediction_upload");

                    b.Navigation("Illness");

                    b.Navigation("ModelVersion");

                    b.Navigation("Tree");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ProcessedImage", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.ImageUpload", "Upload")
                        .WithMany("ProcessedImages")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_processed_upload");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Rating", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Prediction", "Prediction")
                        .WithMany("Ratings")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rating_prediction");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.SolutionCondition", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.TreatmentSolution", "Solution")
                        .WithMany("SolutionConditions")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_condition_solution");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreatmentSolution", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.TreeIllness", "Illness")
                        .WithMany("TreatmentSolutions")
                        .HasForeignKey("IllnessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_treatment_illness");

                    b.HasOne("MyApp.Domain.Entities.TreeStage", "TreeStage")
                        .WithMany("TreatmentSolutions")
                        .HasForeignKey("TreeStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_treatment_stage");

                    b.Navigation("Illness");

                    b.Navigation("TreeStage");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreeIllnessRelationship", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.TreeIllness", "Illness")
                        .WithMany("TreeIllnessRelationships")
                        .HasForeignKey("IllnessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tree_illness_illness");

                    b.HasOne("MyApp.Domain.Entities.Tree", "Tree")
                        .WithMany("TreeIllnessRelationships")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tree_illness_tree");

                    b.Navigation("Illness");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ImageUpload", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("ProcessedImages");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.ModelVersion", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Prediction", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreatmentSolution", b =>
                {
                    b.Navigation("SolutionConditions");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Tree", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("TreeIllnessRelationships");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreeIllness", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("TreatmentSolutions");

                    b.Navigation("TreeIllnessRelationships");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.TreeStage", b =>
                {
                    b.Navigation("TreatmentSolutions");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.User", b =>
                {
                    b.Navigation("ImageUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
